Merged PR 5860521: Support to override cisco sai packages and rpc image

diff --git a/.pipelines/OneBranch.OfficialBuild.yml b/.pipelines/OneBranch.OfficialBuild.yml
--- a/.pipelines/OneBranch.OfficialBuild.yml
+++ b/.pipelines/OneBranch.OfficialBuild.yml
@@ -51,6 +51,7 @@ stages:
     BUILD_OPTIONS: 'SONIC_BUILD_JOBS=4 ENABLE_DHCP_GRAPH_SERVICE=y SHUTDOWN_BGP_ON_START=y ENABLE_PFCWD_ON_START=y SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/$(GROUP_NAME)'
     VERSION_PATH: target/sonic.version
     DOCKER_DATA_ROOT_FOR_MULTIARCCH: /data/march/docker
+    PACKAGE_URL: "https://sonicstorage.blob.core.windows.net/packages"
   jobs:
   - template: ../.azure-pipelines/azure-pipelines-job-groups.yml
     parameters:
@@ -286,6 +287,31 @@ stages:
               tar xvfz $(System.ArtifactsDirectory)/artifactory-*.tar.gz -C platform/cisco-8000
             displayName: 'Setup cisco artifacts'
           - script: |
+              set -ex
+              filename=$(find platform/cisco-8000/artifactory/sonic -name cisco-* -type f | head -n 1)
+              if [ -z "$filename" ]; then
+                echo "Cisco sai package not found" 1>&2
+                exit 1
+              fi
+              cd $(dirname $filename)
+              echo "PWD=$(pwd)"
+              ls -l *.deb
+              while read -r package; do
+                # Cisco version format: <VERSION>-sai-<sai-ver>-<distribution>-<COMMIT HASH>
+                # The <sai-ver> may contain several values in one build, the part is skipped when publishing to storage
+                # See https://github.com/Cisco-8000-sonic/sdk/blob/master/azure-pipelines.yml
+                # The $PACKAGE_URL is only accessible for AZP
+                version=$(echo $package | awk -F_ '{print $(NF-1)}' | cut -d- -f1,2,4,5)
+                package_url="$PACKAGE_URL/sai/ciscosai/master/$version/$package"
+                echo "Override package $package from $package_url"
+                wget "$package_url$StorageSASKey" -O "$package"
+              done < <(ls *.deb)
+            env:
+              StorageSASKey: $(SONIC_PUBLIC_STORAGE_SASKEY)
+            condition: ne(variables['Build.Reason'], 'PullRequest')
+            displayName: "Override cisco sai packages"
+          - script: |
               OPTIONS="$BUILD_OPTIONS ENABLE_NAT=n PASSWORD=$PASSWORD"
               make $OPTIONS target/sonic-cisco-8000.bin
+              make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-rpc.gz
             displayName: JobScript
