fix

diff --git a/.github/workflows/pr_cherrypick_prestep.yml b/.github/workflows/pr_cherrypick_prestep.yml
--- a/.github/workflows/pr_cherrypick_prestep.yml
+++ b/.github/workflows/pr_cherrypick_prestep.yml
@@ -11,9 +11,6 @@ jobs:
   pre_cherry_pick:
     if: github.event.pull_request.merged == true && contains(join(github.event.pull_request.labels.*.name, ','), 'Approved for 20')
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        branch: [202205,202111,202106,202012,201911,201811]
     steps:
     - name: Checkout
       uses: actions/checkout@v3
@@ -36,82 +33,98 @@ jobs:
         pr_url=$(echo $GITHUB_CONTEXT | jq -r ".event.pull_request._links.html.href")
         repository=$(echo $GITHUB_CONTEXT | jq -r ".repository")
         labels_json=$(echo $GITHUB_CONTEXT | jq -r ".event.pull_request.labels[].name")
+        author=$(echo $GITHUB_CONTEXT | jq -r ".event.pull_request.base.user.login")
+        branches=$(git branch -a --list 'origin/20????' | awk -F/ '{print$3}')
         echo =============================
         echo SHA:           $sha
         echo PRID:          $pr_id
         echo pr_url:        $pr_url
         echo repository:    $repository
+        echo branches:      $branches
         echo labels_json:
         echo "$labels_json"
         echo ${TOKEN} | gh auth login --with-token
+        echo author:        $author
         echo =============================
-        if [[ "$(echo $GITHUB_CONTEXT | jq -r '.event.action')" == "labeled" ]] && \
-           [[ "$(echo $GITHUB_CONTEXT | jq -r '.event.label.name')" != "Approved for ${{ matrix.branch }} Branch" ]];then
-          echo "Newly added label didn't match."
-          exit 0
-        fi
-        create_pr=''
-        while read label
-        do
-          echo label: $label
-          if [[ "$label" == "Approved for ${{ matrix.branch }} Branch" ]];then
-            create_pr=1
-          fi
-          if [[ "$label" == "Created PR to ${{ matrix.branch }} Branch" ]];then
-            echo "already has tag: Created PR to ${{ matrix.branch }} Branch, exit"
-            exit 0
-          fi
-          if [[ "$label" == "Included in ${{ matrix.branch }} Branch" ]];then
-            echo "already has tag: Included in ${{ matrix.branch }} Branch, exit"
-            exit 0
-          fi
-        done <<< "$labels_json"
-        if [[ "$create_pr" != "1" ]];then
-          echo "Didn't find 'Approved for ${{ matrix.branch }} Branch' tag."
-          exit 0
-        fi
-
-        # Begin to cherry-pick PR
-        git checkout -b ${{ matrix.branch }} --track origin/${{ matrix.branch }}
-        git checkout .
-        git clean -xdff
 
         git config user.name mssonicbld
         git config user.email sonicbld@microsoft.com
-
         git config credential.https://github.com.username mssonicbld
         git remote add mssonicbld https://mssonicbld:${TOKEN}@github.com/mssonicbld/sonic-buildimage
         git fetch mssonicbld
         git remote -vv
 
-        if ! git cherry-pick $sha;then
-          echo 'cherry-pick failed.'
-          # Add label
-          gh pr edit $pr_url --add-label "Cherry Pick Conflict_${{ matrix.branch }}"
-          echo 'Add label "Cherry Pick Conflict_${{ matrix.branch }}" success'
-          author=$(gh pr view $pr_url --json author | jq '.author.login' | sed 's/"//g')
-          gh pr comment $pr_url --body "@${author} PR conflicts with ${{ matrix.branch }} branch"
-          echo 'Add commnet "@${author} PR conflicts with ${{ matrix.branch }} branch"'
-        else
-          # Create PR to release branch
-          git push mssonicbld HEAD:${{ matrix.branch }}-${pr_id} -f
-          result=$(gh pr create -R ${repository} -H mssonicbld:${{ matrix.branch }}-${pr_id} -B ${{ matrix.branch }} -t "[action] Auto cherry-pick PR:#${pr_id} into ${{ matrix.branch }} branch" -b '')
-          if [[ "$(echo $result | grep github.com)" == "" ]];then echo $result; exit 1;fi
+        cherry_pick(){
+          set -e
+          local create_pr=''
+          local branch=$1
+          if [ -z $branch ];then exit 0;fi
+          while read label
+          do
+            echo label: $label
+            if [[ "$label" == "Approved for $branch Branch" ]];then
+              create_pr=1
+            fi
+            if [[ "$label" == "Created PR to $branch Branch" ]];then
+              echo "already has tag: Created PR to $branch Branch, exit"
+              exit 0
+            fi
+            if [[ "$label" == "Included in $branch Branch" ]];then
+              echo "already has tag: Included in $branch Branch, exit"
+              exit 0
+            fi
+            if [[ "$label" == "Cherry Pick Conflict_$branch" ]];then
+              echo "already has tag: Cherry Pick Conflict_$branch, exit"
+              exit 0
+            fi
+          done <<< "$labels_json"
+          if [[ "$create_pr" != "1" ]];then
+            echo "Didn't find 'Approved for $branch Branch' tag."
+            exit 0
+          fi
+          # Begin to cherry-pick PR
+          git cherry-pick --abort || true
+          git clean -xdff || true
+          git reset HEAD --hard || true
+          git checkout -b $branch --track origin/$branch
+          git status | grep "working tree clean"
 
-          new_pr_rul=$(echo $result | grep github.com)
-          echo new_pr_rul:    $new_pr_rul
+          if ! git cherry-pick $sha;then
+            echo 'cherry-pick failed.'
+            git cherry-pick --abort
+            # Add label
+            gh pr edit $pr_url --add-label "Cherry Pick Conflict_$branch"
+            echo 'Add label "Cherry Pick Conflict_$branch" success'
+            gh pr comment $pr_url --body "@${author} PR conflicts with $branch branch"
+            echo 'Add commnet "@${author} PR conflicts with $branch branch"'
+          else
+            # Create PR to release branch
+            git push mssonicbld HEAD:$branch-${pr_id} -f
+            result=$(gh pr create -R ${repository} -H mssonicbld:$branch-${pr_id} -B $branch -t "[action] Auto cherry-pick PR(#${pr_id}) into $branch branch" -b '')
+            if [[ "$(echo $result | grep github.com)" == "" ]];then echo $result; exit 1;fi
+            new_pr_rul=$(echo $result | grep github.com)
+            echo new_pr_rul:    $new_pr_rul
 
-          # Add label to old PR
-          gh pr edit $pr_url --add-label "Created PR to ${{ matrix.branch }} Branch"
-          echo Add label Created PR to ${{ matrix.branch }} Branch
-          # Add comment to old PR
-          gh pr comment $pr_url --body "Cherry-pick PR to ${{ matrix.branch }}: ${new_pr_rul}"
-          echo Add comment to old PR
+            # Add label to old PR
+            gh pr edit $pr_url --add-label "Created PR to $branch Branch"
+            echo Add label Created PR to $branch Branch
+            # Add comment to old PR
+            gh pr comment $pr_url --body "Cherry-pick PR to $branch: ${new_pr_rul}"
+            echo Add comment to old PR
 
-          # Add label to new PR
-          gh pr edit $new_pr_rul --add-label "automerge"
-          echo Add label automerge to new PR
-          # Add comment to new PR
-          gh pr comment $new_pr_rul --body "Original PR: ${pr_url}"
-          echo Add comment to new PR
-        fi
+            # Add label to new PR
+            gh pr edit $new_pr_rul --add-label "automerge"
+            echo Add label automerge to new PR
+            # Add comment to new PR
+            gh pr comment $new_pr_rul --body "Original PR: ${pr_url}"
+            echo Add comment to new PR
+          fi
+        }
+
+        for branch in $branches
+        do
+          echo -----------------------------
+          echo Begin to parse Branch: $branch
+          cherry_pick $branch
+        done
+
